TRUNCATE TABLE testВb.students_courses RESTART IDENTITY CASCADE;
TRUNCATE TABLE testВb.students RESTART IDENTITY CASCADE;
TRUNCATE TABLE testВb.courses RESTART IDENTITY CASCADE;
TRUNCATE TABLE testВb.groups RESTART IDENTITY CASCADE;
