TRUNCATE TABLE school_app.students_courses RESTART IDENTITY CASCADE;
TRUNCATE TABLE school_app.students RESTART IDENTITY CASCADE;
TRUNCATE TABLE school_app.courses RESTART IDENTITY CASCADE;
TRUNCATE TABLE school_app.groups RESTART IDENTITY CASCADE;
